apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: clone-docker-secret
  annotations:
    policies.kyverno.io/title: Clone Docker registry secret
    policies.kyverno.io/subject: Docker secret, Namespace
    policies.kyverno.io/description: >-
      Clone docker secret to every namespace
spec:
  background: true
  rules:
  - name: clone-docker-secret
    match:
      any:
      - resources:
          kinds:
          - Namespace
    exclude:
      any:
      - resources:
          namespaces:
          - "kube-system"
          - "kube-public"
          - "default"
    generate:
      synchronize: true
      apiVersion: v1
      kind: Secret
      name: docker-gpn.nexign.com
      namespace: "{{request.object.metadata.name}}"
      clone:
        namespace: kyverno
        name: docker-gpn.nexign.com
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: path-default-sa
spec:
  rules:
    - name: path-default-sa
      match:
        any:
        - resources:
            names:
              - default
            kinds:
            - ServiceAccount
      exclude:
        any:
        - resources:
            namespaces:
            - "kube-system"
            - "kube-public"
            - "default"
      mutate:
        patchesJson6902: |-
          - path: "/secrets/-"
            op: add
            value: {"name": "docker-gpn.nexign.com"}
